[{ "fname": "George", "lname": "Todorov", "marks": "4, 5, 6"},
	{ "fname": "Ivan", "lname": "Ivanov", "marks": "4, 5, 6" },
	{ "fname": "Petrov", "lname": "Georgiev", "marks": "4, 5, 6" },
	{ "fname": "Stamat", "lname": "Petrov", "marks": "4, 5, 6" },
	{ "fname": "Nikolay", "lname": "Nikolov", "marks": "4, 5, 6" },
	{ "fname": "Jana", "lname": "Todorova", "marks": "4, 5, 6" },
	{ "fname": "Maria", "lname": "Ivanova", "marks": "4, 5, 6" },
	{ "fname": "Ina", "lname": "Georgieva", "marks": "4, 5, 6" },
	{ "fname": "Denitsa", "lname": "Petrova", "marks": "4, 5, 6" },
	{ "fname": "Kameliya", "lname": "Georgieva", "marks": "4, 5, 6" }]